package mobihoc.session;

public enum NotificationType {
	NULL_NOTIFICATION,
	SUBSCRIBE_RES_NOTIFICATION,
	MESSAGE_IN_NOTIFICATION,
	CONN_OPEN_NOTIFICATION,
	CONN_CLOSE_NOTIFICATION,
	PUBLISH_RES_NOTIFICATION,
	ENABLE_NOTIFICATION,
	DISABLE_NOTIFICATION,
	UPDATE_NOTIFICATION,
	NEW_PUBLISH_NOTIFICATION,
	LOAD_STATE_NOTIFICATION,
	ERROR_NOTIFICATION
}
